First try
VeronikaRevjakina/IOStreams pull request #1
Opened 2019-03-26 21:28 UTC by VeronikaRevjakina

2019-03-28 18:18 UTC, AnnaS91 requested changes

2019-03-28 18:18 UTC, AnnaS91 commented on src/main/java/BinaryStreams.java
> +    /*public static void main(String[] args){
закомментированный код лучше удалять

2019-03-28 18:18 UTC, AnnaS91 commented on src/main/java/BinaryStreams.java
> +            for(int i=0;i<wordsArray.length;i++){
почему не foreach?

2019-03-28 18:18 UTC, AnnaS91 commented on src/main/java/KeywordsFindHelper.java
> +    public static boolean isJavaKeyword(String word){
А почему не захотели объявить keywords как ArrayList и использовать contains?

2019-03-28 18:18 UTC, AnnaS91 commented on src/main/java/BinaryStreams.java
> +            /*bufferedOutputStream.write(("\n" +
почему решили закомментировать?

2019-03-28 18:18 UTC, AnnaS91 commented on src/main/java/TextStreams.java
> +                    ;
что это?)

2019-03-28 18:18 UTC, AnnaS91 commented on src/test/java/KeywordsFindHelperTest.java
> +        assertTrue(!KeywordsFindHelper.isJavaKeyword(word));
assertFalse

2019-03-28 18:18 UTC, AnnaS91 commented on src/test/java/KeywordsFindHelperTest.java
> +        assertTrue(!KeywordsFindHelper.isJavaKeyword(word));
the same

2019-03-28 18:37 UTC, VeronikaRevjakina commented on src/main/java/KeywordsFindHelper.java
> +    public static boolean isJavaKeyword(String word){
Потому что мы ещё их не проходили,а сама не знала,менять и использовать?

2019-03-28 18:38 UTC, VeronikaRevjakina commented on src/main/java/BinaryStreams.java
> +            /*bufferedOutputStream.write(("\n" +
Хотела,чтобы на новую строку переход был,плюс надпись добавить,что это количество ,но потом это в тестах неудобно,так что решила закомментировать

2019-03-28 18:39 UTC, VeronikaRevjakina commented on src/main/java/TextStreams.java
> +                    ;
Пробел после последнего слова записанного в файл

2019-03-28 19:11 UTC, AnnaS91 commented on src/main/java/TextStreams.java
> +                    ;
я про одиноко стоящую точку с запятой

2019-03-28 19:12 UTC, AnnaS91 commented on src/main/java/KeywordsFindHelper.java
> +    public static boolean isJavaKeyword(String word){
аккуратнее будет решение, попробуйте

2019-03-28 19:13 UTC, VeronikaRevjakina commented on src/main/java/TextStreams.java
> +                    ;
Аа видимо усталость)

2019-03-28 19:46 UTC, VeronikaRevjakina commented on src/main/java/KeywordsFindHelper.java
> +    public static boolean isJavaKeyword(String word){
А как добавлять,через add 50 строк ? там же нет инициализации при объявлении насколько я поняла.

2019-03-28 19:50 UTC, AnnaS91 commented on src/main/java/KeywordsFindHelper.java
> +    public static boolean isJavaKeyword(String word){
Вы можете использовать метод Arrays.asList()

2019-03-28 20:01 UTC, VeronikaRevjakina commented on src/main/java/KeywordsFindHelper.java
> +    public static boolean isJavaKeyword(String word){
Спасибо,вроде сделала,только List использовала + сделала private набор самих слов ,но static,потому что дальше в статич-е поле передаются.

2019-03-29 12:47 UTC, AnnaS91 requested changes

2019-03-29 12:47 UTC, AnnaS91 commented on src/main/java/KeywordsFindHelper.java
> +        return (listKeywords.contains(word)) ? true : false;
ой, почему Вы не возвращаете результат contains?

2019-03-29 12:55 UTC, VeronikaRevjakina commented on src/main/java/KeywordsFindHelper.java
> +        return (listKeywords.contains(word)) ? true : false;
Потому что хотела наподобие библиотеки одной сделать,изначально хотела её метод подключить,но там легче было самой метод прописать. И потом легче в if использовать в цикле boolean, могу ,конечно,исправить,но не очень понимаю чем это лучше.

2019-03-29 12:57 UTC, VeronikaRevjakina commented on src/main/java/KeywordsFindHelper.java
> +        return (listKeywords.contains(word)) ? true : false;
Всё дошло,я неправильно поняла что contains возвращает,почитала доки,сейчас исправлю.

2019-03-29 13:06 UTC, AnnaS91 approved these changes

2019-03-29 13:22 UTC, merged